# Generated by Django 4.1.4 on 2022-12-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_orders_address_orders_amount_orders_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
