# Generated by Django 4.1.4 on 2022-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_address_orders_address1_orders_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_orderd',
            field=models.BooleanField(default=False),
        ),
    ]
